Update Requirements for Presubmit Tests Temporarily (#2770)
1. This pr updates requirements for presubmit tests temporarily till
below error due to llvm-project integration in
iree([6a927feeef80304fffbf550910538f5d5b94678f](https://github.com/iree-org/iree/commit/6a927feeef80304fffbf550910538f5d5b94678f))
is solved

File "iree-turbine/iree/turbine/dynamo/type_conversion.py", line 102, in
convert_torch_element_type_to_native
if IntegerType.isinstance(torch_type):
^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object
'iree.compiler._mlir_libs._mlir.ir.IntegerType' has no attribute
'isinstance'


issue is filed here ->
https://github.com/iree-org/iree-turbine/issues/1267


2. Replacing use of wave with latest release version using pip install
wave-lang